import os
import secrets
import stat
from pathlib import Path


def generate_secrets() -> dict:
    return {
        "db_password": secrets.token_urlsafe(24),
        "redis_password": secrets.token_urlsafe(24),
        "secret_key": secrets.token_hex(32),
    }


def assemble_env(state: dict) -> str:
    db_pw = state["db_password"]
    redis_pw = state["redis_password"]
    lines = [
        "# IRDoc environment — generated by installer/wizard.py",
        "# Do not commit this file.",
        "",
        "# ─── Database ─────────────────────────────────────────────────────────────────",
        f"DB_PASSWORD={db_pw}",
        f"DATABASE_URL=postgresql+asyncpg://irp:{db_pw}@irdoc-db/irp",
        "",
        "# ─── Redis ──────────────────────────────────────────────────────────────────",
        f"REDIS_PASSWORD={redis_pw}",
        f"REDIS_URL=redis://:{redis_pw}@irdoc-redis:6379/0",
        "",
        "# ─── Security ───────────────────────────────────────────────────────────────",
        f"SECRET_KEY={state['secret_key']}",
        f"ACCESS_TOKEN_EXPIRE_MINUTES={state['access_token_expire_minutes']}",
        f"REFRESH_TOKEN_EXPIRE_DAYS={state['refresh_token_expire_days']}",
        "",
        "# ─── Application ────────────────────────────────────────────────────────────",
        f"BASE_URL={state['base_url']}",
        "ALLOW_REGISTRATION=false",
        f"LICENSE_KEY={state.get('license_key', '')}",
        "",
        "# ─── Storage ────────────────────────────────────────────────────────────────",
        "STORAGE_BACKEND=local",
        "STORAGE_PATH=/app/storage",
        "",
        "# ─── Webhooks ───────────────────────────────────────────────────────────────",
        "WEBHOOK_RATE_LIMIT=20",
        "WEBHOOK_MAX_PAYLOAD_BYTES=65536",
    ]
    return "\n".join(lines) + "\n"


def read_existing_env(path: Path) -> dict:
    result = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, value = line.partition("=")
            result[key.strip()] = value.strip()
    return result


def write_env(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8")
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)  # 0o600
